#!/bin/bash

# Check if a commit message was provided
if [ -z "$1" ]; then
  echo "Error: Commit message is required."
  exit 1
fi

# Run git commands
git add .
git commit -m "$1"
git push

echo "Changes pushed to remote."

# make the script executable: chmod +x up
# run it like ./up "commit message"

